# Generated by Django 2.2.1 on 2019-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('c_no', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
                ('agent', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='agent/')),
                ('address', models.CharField(max_length=50)),
                ('c_no', models.IntegerField()),
            ],
        ),
    ]
