# Generated by Django 2.2.1 on 2019-06-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('client_uname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='client/')),
                ('c_no', models.IntegerField()),
                ('adress', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=30)),
                ('client_uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
            ],
        ),
    ]
