# Generated by Django 2.1.7 on 2019-06-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='client_uname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='os_client.Client'),
        ),
    ]
