# Generated by Django 2.1.7 on 2019-08-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_client', '0002_auto_20190614_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='c_no',
        ),
        migrations.AddField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
