# Generated by Django 2.1.7 on 2019-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_client', '0003_auto_20190824_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='cont',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
