# Generated by Django 2.1.7 on 2019-08-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_client', '0004_complaint_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='cont',
            field=models.IntegerField(default=None),
        ),
    ]
