# Generated by Django 2.2.1 on 2019-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_agent', '0002_auto_20190606_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sold_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
