# Generated by Django 2.2.1 on 2019-06-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_agent', '0003_auto_20190606_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyblocked',
            name='amount',
        ),
    ]
