# Generated by Django 2.2.1 on 2019-06-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_client', '0001_initial'),
        ('os_agent', '0004_remove_propertyblocked_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproperty',
            name='client_uname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='os_client.Client'),
        ),
    ]
